# Generated by Django 4.0.4 on 2022-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtextfile',
            name='unique_title',
            field=models.CharField(max_length=54, null=True, verbose_name='Unique title'),
        ),
    ]
