# Generated by Django 4.0.4 on 2022-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_addtextfile_unique_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtextfile',
            name='unique_number',
            field=models.IntegerField(max_length=16, null=True, verbose_name='Unique number'),
        ),
    ]
