# Generated by Django 4.0.4 on 2022-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_addtextfile_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtextfile',
            name='unique_number',
            field=models.IntegerField(null=True, verbose_name='Unique number'),
        ),
    ]
